package com.example.cyberdeck.cyberware;

import java.util.Set;

/** Catalog-to-runtime coverage contract for data-driven cyberware mechanics. */
public final class CyberwareMechanics {
    private static final Set<String> IMPLEMENTED_FLAGS = Set.of(
            "behavioral_identity",
            "berserk",
            "biomonitor",
            "blackwall_gateway",
            "blood_pump",
            "burst_damage_mitigation",
            "charged_jump",
            "chrome_compressor",
            "combat_entry_speed",
            "crouch_armor",
            "cyberdeck",
            "damage_chemical",
            "damage_electrical",
            "damage_physical",
            "damage_reactive_shock",
            "damage_thermal",
            "damage_to_dot",
            "detection_speed",
            "detection_time_slow",
            "device_specialist",
            "distance_crit",
            "double_jump",
            "gorilla_arms",
            "health_item_boost",
            "health_on_kill",
            "health_on_tech_hit",
            "health_regen",
            "health_stamina_on_tech_hit",
            "high_stamina_mitigation",
            "invulnerable",
            "kerenzikov",
            "kerenzikov_boost",
            "kiroshi_optics",
            "low_health_armor",
            "low_health_speed",
            "low_health_time_slow",
            "low_ram_armor",
            "low_ram_regen",
            "low_ram_restore",
            "mantis_blades",
            "melee_attack_speed",
            "melee_only",
            "monowire",
            "optical_camo",
            "paraline",
            "poison_synergy",
            "post_kerenzikov_mitigation",
            "projectile_block",
            "projectile_launcher",
            "proximity_damage_reduction",
            "quantum_tuner",
            "quickhack_combo",
            "quickhack_crit",
            "quickhack_dot",
            "quickhack_spread",
            "quiet_steps",
            "ram_on_damage",
            "range_armor",
            "rear_armor",
            "reload_shock",
            "ricochet",
            "sandevistan",
            "scanner_highlight",
            "second_heart",
            "self_ice",
            "smart_targeting",
            "sprint_ramp",
            "status_bleeding",
            "status_burn",
            "status_poison",
            "status_shock",
            "subdermal_armor",
            "takedown_boost",
            "takedown_ram",
            "tech_targeting",
            "technical_adaptation",
            "throwable_crit");

    private static final Set<String> IMPLEMENTED_VALUES = Set.of(
            "active_attack_speed_percent",
            "active_crit_chance_percent",
            "active_crit_damage_percent",
            "active_damage_percent",
            "active_damage_reduction_percent",
            "active_movement_speed_percent",
            "airborne_damage_percent",
            "airborne_headshot_percent",
            "airborne_time_slow_percent",
            "armor_multiplier_percent",
            "armor_points",
            "attack_speed_percent",
            "blade_crit_chance_percent",
            "blood_pump_instant_health",
            "blood_pump_regen_per_second",
            "capacity_bonus",
            "carry_capacity_percent",
            "close_damage_reduction_percent",
            "combat_speed_percent",
            "combat_speed_seconds",
            "conditional_armor_percent",
            "cooldown_on_kill_percent",
            "cooldown_reduction_percent",
            "cooldown_restore_max_seconds",
            "cooldown_seconds",
            "crit_chance_percent",
            "crit_damage_percent",
            "critical_health_speed_percent",
            "crouch_armor",
            "crouch_speed_penalty_percent",
            "crouch_speed_percent",
            "damage_to_dot_percent",
            "detection_reduction_percent",
            "detection_speed_percent",
            "distance_crit_percent",
            "distance_crit_range",
            "duration_seconds",
            "elemental_resistance_percent",
            "explosion_resistance_percent",
            "fall_damage_reduction_percent",
            "grenade_cooldown_reduction_percent",
            "headshot_damage_percent",
            "health_item_armor_percent",
            "health_item_cooldown_reduction_percent",
            "health_item_effectiveness_percent",
            "health_item_stamina_reduction_percent",
            "health_on_kill_percent",
            "health_on_tech_hit_percent",
            "health_stamina_on_tech_hit_percent",
            "incoming_damage_reduction_percent",
            "kill_duration_percent",
            "kill_headshot_percent",
            "kill_health_percent",
            "kill_movement_percent",
            "kill_stamina_percent",
            "low_health_speed_percent",
            "low_ram_armor_percent",
            "low_ram_regen_percent",
            "low_ram_restore_percent",
            "low_ram_threshold",
            "low_ram_threshold_percent",
            "max_health_percent",
            "max_ram",
            "mechanical_damage_percent",
            "melee_damage_percent",
            "mitigation_chance_percent",
            "mitigation_strength_percent",
            "monowire_dot_damage_percent",
            "monowire_ram_damage_cap_percent",
            "monowire_ram_damage_percent",
            "movement_speed_percent",
            "poison_other_damage_percent",
            "projectile_block_chance_percent",
            "quickhack_crit_chance_percent",
            "quickhack_combo_damage_percent",
            "quickhack_damage_percent",
            "quickhack_dot_damage_percent",
            "quickhack_duration_percent",
            "quickhack_ram_cost_reduction_percent",
            "quickhack_spread_distance_percent",
            "quickhack_upload_speed_percent",
            "quiet_movement_percent",
            "ram_damage_percent",
            "ram_on_kill",
            "ram_regen_per_second",
            "range_armor",
            "ranged_stamina_reduction_percent",
            "rear_armor_percent",
            "recoil_reduction_percent",
            "reload_shock_damage",
            "ricochet_chance_percent",
            "ricochet_damage_percent",
            "scanner_device_range",
            "scanner_enemy_range",
            "scanner_explosive_range",
            "scanner_wall_range",
            "shock_chance_percent",
            "shock_damage",
            "smart_crit_damage_percent",
            "smart_lock_duration_percent",
            "smart_lock_speed_percent",
            "spread_reduction_percent",
            "sprint_speed_end_percent",
            "sprint_speed_start_percent",
            "stamina_on_melee_kill_percent",
            "stamina_reduction_percent",
            "status_chance_percent",
            "takedown_ram",
            "tech_weapon_damage_percent",
            "throwable_crit_chance_percent",
            "time_slow_bonus_percent",
            "time_slow_percent",
            "trigger_cooldown_seconds",
            "visibility_reduction_percent");

    private CyberwareMechanics() {
    }

    public static boolean implementsFlag(String flag) {
        return IMPLEMENTED_FLAGS.contains(flag);
    }

    public static boolean implementsValue(String value) {
        return IMPLEMENTED_VALUES.contains(value);
    }

    public static boolean hasRuntimeEffect(Cyberware cyberware) {
        return cyberware != null
                && (cyberware.flags().stream().anyMatch(CyberwareMechanics::implementsFlag)
                        || cyberware.values().keySet().stream()
                                .anyMatch(CyberwareMechanics::implementsValue));
    }
}
