package com.example.cyberdeck.client.map;

import dev.modernity.neoncity.District;
import dev.modernity.neoncity.MegacityLayout;
import java.util.ArrayList;
import java.util.List;

/**
 * Client-side source of merchant location markers for the minimap and full city map.
 *
 * <p>Merchant truck parks are generated by {@code MerchantTruckLibrary} in clusters anchored to
 * each district's layout node, so the district node position is the stable, world-independent
 * center of a district's merchant presence. Exact per-truck coordinates require server world-gen
 * sampling ({@code NeonCityGenerator.sampleChunk}) that is not available on the client, so we
 * expose one marker per district at its node using the same {@link MegacityLayout} the client
 * already holds. This keeps merchant markers deterministic and requires no server or packet
 * changes.</p>
 */
public final class MerchantMarkerClient {
    /** Amber accent used for merchant markers, distinct from routes and player color. */
    public static final int MERCHANT_COLOR = 0xFFFF9F3C;
    public static final int MERCHANT_SHADOW = 0xE005090C;

    private MerchantMarkerClient() {
    }

    /** One merchant marker per district, sourced from the shared city layout. */
    public static List<Marker> markers(MegacityLayout layout) {
        if (layout == null) {
            return List.of();
        }
        List<Marker> markers = new ArrayList<>(layout.nodes().size());
        for (MegacityLayout.Node node : layout.nodes()) {
            District district = node.district();
            markers.add(new Marker(
                    node.x(),
                    node.z(),
                    district.code(),
                    district.label() + " Merchants"));
        }
        return List.copyOf(markers);
    }

    public record Marker(int x, int z, String districtCode, String label) {
    }
}
