package dev.modernity.neoncity;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraft.world.level.block.state.BlockState;

/** Seeded U Corp coastline, container terminal, deep ocean, and floating Portships. */
public final class UCorpPortGeneration {
    public static final int PORTSHIP_SIZE = 75;
    public static final int PORTSHIP_HALF = PORTSHIP_SIZE / 2;
    public static final int MIN_PORTSHIPS = 2;
    public static final int MAX_PORTSHIPS = 3;
    public static final int OCEAN_FLOOR_MIN_Y = 50;
    public static final int OVERLAY_MIN_Y = 63;
    public static final int OVERLAY_MAX_Y = 116;

    private static final long PLAN_SALT = 0x55434F52504F5254L;
    private static final long CONTAINER_SALT = 0x434F4E5441494E52L;
    private static final long PORTSHIP_SALT = 0x504F525453484950L;
    private static final int[][] CARDINAL_DIRECTIONS = {
            {1, 0}, {0, 1}, {-1, 0}, {0, -1}
    };
    private static final DyeColor[] CONTAINER_COLORS = {
            DyeColor.BLUE,
            DyeColor.LIGHT_BLUE,
            DyeColor.CYAN,
            DyeColor.GREEN,
            DyeColor.ORANGE,
            DyeColor.YELLOW,
            DyeColor.RED,
            DyeColor.GRAY
    };
    private static final Map<Long, Plan> PLAN_CACHE = new ConcurrentHashMap<>();

    private UCorpPortGeneration() {
    }

    public enum Feature {
        NONE,
        CONTAINER_PORT,
        HARBOR_WATER,
        OCEAN,
        PORTSHIP
    }

    /** One 75x75 floating settlement, generated by global-coordinate sampling. */
    public record Portship(int index, int centerX, int centerZ, long identity) {
        public int minX() {
            return centerX - PORTSHIP_HALF;
        }

        public int maxX() {
            return centerX + PORTSHIP_HALF;
        }

        public int minZ() {
            return centerZ - PORTSHIP_HALF;
        }

        public int maxZ() {
            return centerZ + PORTSHIP_HALF;
        }
    }

    /** Pure seed-bound marine plan shared by runtime generation, maps, and tests. */
    public record Plan(
            long layoutSeed,
            int originX,
            int originZ,
            int forwardX,
            int forwardZ,
            int rightX,
            int rightZ,
            int portStart,
            int shoreline,
            int oceanEnd,
            int oceanHalfWidth,
            long identity,
            List<Portship> portships) {
        public Plan {
            portships = List.copyOf(portships);
        }

        public int forwardAt(int worldX, int worldZ) {
            return (worldX - originX) * forwardX + (worldZ - originZ) * forwardZ;
        }

        public int lateralAt(int worldX, int worldZ) {
            return (worldX - originX) * rightX + (worldZ - originZ) * rightZ;
        }

        public int worldX(int forward, int lateral) {
            return originX + forward * forwardX + lateral * rightX;
        }

        public int worldZ(int forward, int lateral) {
            return originZ + forward * forwardZ + lateral * rightZ;
        }

        public int shorelineAt(int lateral) {
            double phase = ((identity >>> 11) & 0xFFFF) / 65535.0 * Math.PI * 2.0;
            return shoreline + (int) Math.round(
                    13.0 * Math.sin(lateral / 47.0 + phase)
                            + 7.0 * Math.sin(lateral / 19.0 - phase * 0.6));
        }

        public Feature featureAt(int worldX, int worldZ) {
            Portship ship = portshipAt(worldX, worldZ);
            if (ship != null) {
                return Feature.PORTSHIP;
            }
            int forward = forwardAt(worldX, worldZ);
            int lateral = lateralAt(worldX, worldZ);
            if (Math.abs(lateral) > oceanHalfWidth) {
                return Feature.NONE;
            }
            int localShoreline = shorelineAt(lateral);
            if (forward >= localShoreline && forward <= oceanEnd) {
                return Feature.OCEAN;
            }
            if (forward < portStart || forward >= localShoreline) {
                return Feature.NONE;
            }
            int basin = Math.floorMod(lateral + (int) identity, 112);
            if (forward >= portStart + 24 && basin < 14) {
                return Feature.HARBOR_WATER;
            }
            return Feature.CONTAINER_PORT;
        }

        public boolean isManagedAt(int worldX, int worldZ) {
            return featureAt(worldX, worldZ) != Feature.NONE;
        }

        public boolean isOceanBiomeAt(int worldX, int worldZ) {
            return switch (featureAt(worldX, worldZ)) {
                case HARBOR_WATER, OCEAN, PORTSHIP -> true;
                default -> false;
            };
        }

        public Portship portshipAt(int worldX, int worldZ) {
            for (Portship ship : portships) {
                int localForward = (worldX - ship.centerX()) * forwardX
                        + (worldZ - ship.centerZ()) * forwardZ;
                int localLateral = (worldX - ship.centerX()) * rightX
                        + (worldZ - ship.centerZ()) * rightZ;
                if (portshipContains(localForward, localLateral)) {
                    return ship;
                }
            }
            return null;
        }

        public boolean chunkIntersectsManagedArea(int chunkX, int chunkZ) {
            int minX = chunkX << 4;
            int minZ = chunkZ << 4;
            for (int dz = 0; dz < 16; dz++) {
                for (int dx = 0; dx < 16; dx++) {
                    if (isManagedAt(minX + dx, minZ + dz)) {
                        return true;
                    }
                }
            }
            return false;
        }

        public int maximumAbsoluteCoordinate() {
            int result = 0;
            int[] forwards = {portStart, oceanEnd};
            int[] laterals = {-oceanHalfWidth, oceanHalfWidth};
            for (int forward : forwards) {
                for (int lateral : laterals) {
                    result = Math.max(result, Math.abs(worldX(forward, lateral)));
                    result = Math.max(result, Math.abs(worldZ(forward, lateral)));
                }
            }
            for (Portship ship : portships) {
                result = Math.max(result, Math.abs(ship.centerX()) + PORTSHIP_HALF);
                result = Math.max(result, Math.abs(ship.centerZ()) + PORTSHIP_HALF);
            }
            return result;
        }
    }

    public static Plan plan(MegacityLayout layout) {
        if (PLAN_CACHE.size() > 64) {
            PLAN_CACHE.clear();
        }
        return PLAN_CACHE.computeIfAbsent(layout.seed(), ignored -> createPlan(layout));
    }

    public static void clearCache() {
        PLAN_CACHE.clear();
    }

    private static Plan createPlan(MegacityLayout layout) {
        MegacityLayout.Node node = layout.node(District.U_CORP);
        long identity = MegacityLayout.mix(layout.seed() ^ PLAN_SALT, node.x(), node.z());
        int shipCount = MIN_PORTSHIPS + Math.floorMod((int) identity, 2);
        int[] direction = chooseCoastDirection(layout, node, shipCount);
        int forwardX = direction[0];
        int forwardZ = direction[1];
        int rightX = -forwardZ;
        int rightZ = forwardX;
        int forwardRadius = (int) Math.round(directionalRadius(node, forwardX, forwardZ));
        int lateralRadius = (int) Math.round(directionalRadius(node, rightX, rightZ));
        int portStart = (int) Math.round(forwardRadius * 0.50);
        int shoreline = (int) Math.round(forwardRadius * 0.72);
        int oceanHalfWidth = Math.min(520, Math.max(360, (int) Math.round(lateralRadius * 0.42)));
        int shipBaseForward = (int) Math.round(forwardRadius * 1.12) + 120;
        ArrayList<Portship> ships = new ArrayList<>(shipCount);
        for (int index = 0; index < shipCount; index++) {
            long shipIdentity = MegacityLayout.mix(identity ^ PORTSHIP_SALT, index, shipCount);
            double lateralFactor = shipCount == 2
                    ? (index == 0 ? -0.28 : 0.28)
                    : (index - 1) * 0.31;
            int shipForward = shipBaseForward + (index % 2) * 135
                    + signedRange(shipIdentity, 17);
            int shipLateral = (int) Math.round(oceanHalfWidth * lateralFactor)
                    + signedRange(Long.rotateLeft(shipIdentity, 23), 16);
            ships.add(new Portship(
                    index,
                    node.x() + shipForward * forwardX + shipLateral * rightX,
                    node.z() + shipForward * forwardZ + shipLateral * rightZ,
                    shipIdentity));
        }
        int oceanEnd = ships.stream()
                .mapToInt(ship -> (ship.centerX() - node.x()) * forwardX
                        + (ship.centerZ() - node.z()) * forwardZ)
                .max().orElse(shipBaseForward) + PORTSHIP_HALF + 90;
        return new Plan(
                layout.seed(), node.x(), node.z(),
                forwardX, forwardZ, rightX, rightZ,
                portStart, shoreline, oceanEnd, oceanHalfWidth,
                identity, ships);
    }

    private static int[] chooseCoastDirection(
            MegacityLayout layout, MegacityLayout.Node node, int shipCount) {
        double centerLength = Math.max(1.0, Math.hypot(node.x(), node.z()));
        int[] best = CARDINAL_DIRECTIONS[0];
        double bestScore = -Double.MAX_VALUE;
        for (int[] direction : CARDINAL_DIRECTIONS) {
            double forwardRadius = directionalRadius(node, direction[0], direction[1]);
            double lateralRadius = directionalRadius(node, -direction[1], direction[0]);
            double halfWidth = Math.min(520.0, Math.max(360.0, lateralRadius * 0.42));
            double shipBase = forwardRadius * 1.12 + 120.0;
            double clearance = Double.MAX_VALUE;
            double[] forwardSamples = {
                    forwardRadius * 0.72,
                    forwardRadius * 1.08,
                    shipBase,
                    shipBase + (shipCount > 1 ? 135.0 : 0.0)
            };
            double[] lateralSamples = {-halfWidth * 0.34, 0.0, halfWidth * 0.34};
            for (MegacityLayout.Node other : layout.nodes()) {
                if (other.district() == District.U_CORP) continue;
                for (double forward : forwardSamples) {
                    for (double lateral : lateralSamples) {
                        int x = (int) Math.round(node.x() + forward * direction[0]
                                - lateral * direction[1]);
                        int z = (int) Math.round(node.z() + forward * direction[1]
                                + lateral * direction[0]);
                        clearance = Math.min(clearance, layout.normalizedDistanceTo(other, x, z));
                    }
                }
            }
            double outwardAlignment = (node.x() * direction[0] + node.z() * direction[1])
                    / centerLength;
            double score = clearance * 4.0 + outwardAlignment * 2.5;
            if (score > bestScore) {
                bestScore = score;
                best = direction;
            }
        }
        return best;
    }

    private static double directionalRadius(
            MegacityLayout.Node node, double directionX, double directionZ) {
        double cosine = Math.cos(node.rotation());
        double sine = Math.sin(node.rotation());
        double localX = directionX * cosine + directionZ * sine;
        double localZ = -directionX * sine + directionZ * cosine;
        return 1.0 / Math.sqrt(
                localX * localX / (node.radiusX() * (double) node.radiusX())
                        + localZ * localZ / (node.radiusZ() * (double) node.radiusZ()));
    }

    static boolean portshipContains(int localForward, int localLateral) {
        int forward = Math.abs(localForward);
        int lateral = Math.abs(localLateral);
        if (forward > PORTSHIP_HALF || lateral > PORTSHIP_HALF) {
            return false;
        }
        return Math.max(0, forward - 29) + Math.max(0, lateral - 29) <= 11;
    }

    /** Returns a non-air overlay block for port/Portship architecture, or {@code null}. */
    static BlockState overlayAt(Plan plan, int worldX, int y, int worldZ) {
        Feature feature = plan.featureAt(worldX, worldZ);
        return switch (feature) {
            case CONTAINER_PORT -> portOverlayAt(plan, worldX, y, worldZ);
            case PORTSHIP -> portshipOverlayAt(plan, worldX, y, worldZ);
            default -> null;
        };
    }

    private static BlockState portOverlayAt(Plan plan, int worldX, int y, int worldZ) {
        int forward = plan.forwardAt(worldX, worldZ);
        int lateral = plan.lateralAt(worldX, worldZ);
        BlockState crane = portCraneAt(plan, forward, lateral, y);
        if (crane != null) {
            return crane;
        }
        if (y == NeonCityGenerator.CITY_GROUND_Y + 1
                && Math.floorMod(lateral, 18) == 0
                && Math.floorMod(forward, 23) == 0) {
            return Blocks.OCHRE_FROGLIGHT.defaultBlockState();
        }
        int depth = forward - plan.portStart();
        int row = Math.floorDiv(depth, 10);
        int aisle = Math.floorDiv(lateral + plan.oceanHalfWidth(), 32);
        if (Math.floorMod(row, 5) == 4 || Math.floorMod(aisle, 6) == 5) {
            return null;
        }
        int localWidth = Math.floorMod(depth, 10);
        int localLength = Math.floorMod(lateral + plan.oceanHalfWidth(), 32);
        if (localWidth >= 7 || localLength >= 28) {
            return null;
        }
        long hash = MegacityLayout.mix(plan.identity() ^ CONTAINER_SALT, row, aisle);
        if (unit(hash) > 0.82) {
            return null;
        }
        int stacks = 1 + Math.floorMod((int) (hash >>> 17), 3);
        return stackedContainerAt(
                y,
                NeonCityGenerator.CITY_GROUND_Y + 1,
                localWidth,
                localLength,
                7,
                28,
                stacks,
                hash,
                false);
    }

    private static BlockState portCraneAt(Plan plan, int forward, int lateral, int y) {
        int craneForward = portCraneForward(plan);
        for (int index = 0; index < 3; index++) {
            int lateralAnchor = portCraneLateral(plan, index);
            int df = forward - craneForward;
            int dl = lateral - lateralAnchor;
            BlockState state = craneAt(df, dl, y, NeonCityGenerator.CITY_GROUND_Y + 1, 29, index);
            if (state != null) return state;
        }
        return null;
    }

    static int portCraneForward(Plan plan) {
        // shorelineAt can retreat by up to twenty blocks; keep the full 44-block boom inland.
        return plan.shoreline() - 64;
    }

    static int portCraneLateral(Plan plan, int index) {
        int target = switch (index) {
            case 0 -> -plan.oceanHalfWidth() * 3 / 5;
            case 1 -> 0;
            case 2 -> plan.oceanHalfWidth() * 3 / 5;
            default -> throw new IllegalArgumentException("crane index must be 0..2");
        };
        return safeCraneLateral(plan, target);
    }

    private static int safeCraneLateral(Plan plan, int target) {
        int basin = Math.floorMod(target + (int) plan.identity(), 112);
        if (basin < 17) return target + 17 - basin;
        if (basin > 110) return target - (basin - 110);
        return target;
    }

    private static BlockState portshipOverlayAt(Plan plan, int worldX, int y, int worldZ) {
        Portship ship = plan.portshipAt(worldX, worldZ);
        if (ship == null) return null;
        int forward = (worldX - ship.centerX()) * plan.forwardX()
                + (worldZ - ship.centerZ()) * plan.forwardZ();
        int lateral = (worldX - ship.centerX()) * plan.rightX()
                + (worldZ - ship.centerZ()) * plan.rightZ();
        boolean edge = isPortshipEdge(forward, lateral);
        if (y >= NeonCityGenerator.WATER_Y - 3 && y <= NeonCityGenerator.WATER_Y + 1) {
            if (edge) {
                return ((y + forward + lateral) & 1) == 0
                        ? Blocks.POLISHED_BLACKSTONE_BRICKS.defaultBlockState()
                        : Blocks.IRON_BLOCK.defaultBlockState();
            }
            if (y == NeonCityGenerator.WATER_Y + 1) {
                return Blocks.IRON_BLOCK.defaultBlockState();
            }
        }
        if (y == NeonCityGenerator.WATER_Y + 2) {
            if (Math.abs(forward) <= 3 || Math.abs(lateral) <= 3) {
                return Blocks.POLISHED_DEEPSLATE.defaultBlockState();
            }
            return Math.floorMod(forward + lateral, 11) == 0
                    ? Blocks.CUT_COPPER.weathering()
                            .pick(WeatheringCopper.WeatherState.EXPOSED)
                            .defaultBlockState()
                    : Blocks.DARK_OAK_PLANKS.defaultBlockState();
        }
        if (edge && y == NeonCityGenerator.WATER_Y + 3
                && Math.floorMod(forward * 7 + lateral * 11, 9) != 0) {
            return Blocks.IRON_BARS.defaultBlockState();
        }

        BlockState crane = craneAt(
                forward + 5,
                lateral + 25,
                y,
                NeonCityGenerator.WATER_Y + 3,
                24,
                ship.index());
        if (crane != null) return crane;
        BlockState tower = centralTowerAt(ship, forward, lateral, y);
        if (tower != null) return tower;
        return favelaContainerAt(ship, forward, lateral, y);
    }

    private static BlockState centralTowerAt(
            Portship ship, int forward, int lateral, int y) {
        if (ship.index() != 0 || Math.abs(forward) > 6 || Math.abs(lateral) > 6) {
            return null;
        }
        int baseY = NeonCityGenerator.WATER_Y + 3;
        int relativeY = y - baseY;
        if (relativeY < 0 || relativeY > 35) return null;
        int radius = relativeY > 27 ? 4 : relativeY > 17 ? 5 : 6;
        if (Math.abs(forward) > radius || Math.abs(lateral) > radius) return null;
        boolean shell = Math.abs(forward) == radius || Math.abs(lateral) == radius
                || relativeY == 0 || relativeY == 35;
        if (!shell) return null;
        if (relativeY >= 11 && relativeY <= 13 || relativeY >= 23 && relativeY <= 25) {
            return Blocks.STAINED_GLASS.pick(DyeColor.LIGHT_BLUE).defaultBlockState();
        }
        return (forward + lateral + relativeY) % 7 == 0
                ? Blocks.SEA_LANTERN.defaultBlockState()
                : Blocks.CONCRETE.pick(DyeColor.WHITE).defaultBlockState();
    }

    private static BlockState favelaContainerAt(
            Portship ship, int forward, int lateral, int y) {
        if (Math.abs(forward) > 32 || Math.abs(lateral) > 32
                || Math.abs(forward) <= 3 || Math.abs(lateral) <= 3) {
            return null;
        }
        int cellForward = Math.floorDiv(forward + 33, 11);
        int cellLateral = Math.floorDiv(lateral + 33, 11);
        if (cellForward < 0 || cellForward >= 6 || cellLateral < 0 || cellLateral >= 6) {
            return null;
        }
        long cellHash = MegacityLayout.mix(
                ship.identity() ^ CONTAINER_SALT, cellForward, cellLateral);
        if (unit(cellHash) > 0.86) {
            return null;
        }
        int levels = 2 + Math.floorMod((int) (cellHash >>> 19), 3);
        int cellOriginForward = -33 + cellForward * 11;
        int cellOriginLateral = -33 + cellLateral * 11;
        int baseY = NeonCityGenerator.WATER_Y + 3;
        for (int level = levels - 1; level >= 0; level--) {
            long levelHash = MegacityLayout.mix(cellHash ^ PORTSHIP_SALT, level, levels);
            int offsetForward = level == 0 ? 1 : signedRange(levelHash, 2) + 1;
            int offsetLateral = level == 0 ? 1 : signedRange(Long.rotateLeft(levelHash, 17), 2) + 1;
            boolean turn = ((levelHash >>> 8) & 1L) != 0L;
            int sizeForward = turn ? 9 : 7;
            int sizeLateral = turn ? 7 : 9;
            int relativeForward = forward - (cellOriginForward + offsetForward);
            int relativeLateral = lateral - (cellOriginLateral + offsetLateral);
            if (relativeForward < 0 || relativeForward >= sizeForward
                    || relativeLateral < 0 || relativeLateral >= sizeLateral) {
                continue;
            }
            BlockState state = stackedContainerAt(
                    y,
                    baseY + level * 7,
                    relativeForward,
                    relativeLateral,
                    sizeForward,
                    sizeLateral,
                    1,
                    levelHash,
                    true);
            if (state != null) return state;
            int roofY = baseY + (level + 1) * 7;
            if (y == roofY + 1
                    && relativeForward == sizeForward / 2
                    && relativeLateral == sizeLateral / 2
                    && Math.floorMod((int) levelHash, 5) == 0) {
                return Blocks.END_ROD.defaultBlockState();
            }
        }
        return null;
    }

    private static BlockState stackedContainerAt(
            int y,
            int baseY,
            int localWidth,
            int localLength,
            int width,
            int length,
            int stacks,
            long hash,
            boolean windows) {
        for (int stack = stacks - 1; stack >= 0; stack--) {
            int levelBase = baseY + stack * 7;
            int localY = y - levelBase;
            if (localY < 0 || localY >= 7) continue;
            boolean floorOrRoof = localY == 0 || localY == 6;
            boolean side = localWidth == 0 || localWidth == width - 1
                    || localLength == 0 || localLength == length - 1;
            if (!floorOrRoof && !side) return null;
            long levelHash = Long.rotateLeft(hash, stack * 11);
            BlockState color = containerColor(levelHash);
            boolean frame = (localWidth == 0 || localWidth == width - 1)
                    && (localLength == 0 || localLength == length - 1)
                    || side && localLength % 4 == 0
                    || side && localY == 5;
            if (frame) {
                return Blocks.CONCRETE.pick(DyeColor.LIGHT_GRAY).defaultBlockState();
            }
            if (windows && side && localY >= 2 && localY <= 3
                    && Math.floorMod(localWidth * 5 + localLength * 3, 7) <= 1) {
                return Blocks.TINTED_GLASS.defaultBlockState();
            }
            if (side && localY >= 1 && localY <= 4
                    && localLength == 0 && localWidth >= width / 2 - 1
                    && localWidth <= width / 2 + 1) {
                return Blocks.IRON_BARS.defaultBlockState();
            }
            return color;
        }
        return null;
    }

    private static BlockState craneAt(
            int localForward,
            int localLateral,
            int y,
            int baseY,
            int height,
            int variant) {
        int top = baseY + height;
        if (Math.abs(localForward) <= 1 && Math.abs(localLateral) <= 1
                && y >= baseY && y <= top) {
            return Math.floorMod(y + variant, 4) == 0
                    ? Blocks.IRON_BLOCK.defaultBlockState()
                    : Blocks.CONCRETE.pick(DyeColor.YELLOW).defaultBlockState();
        }
        if (localLateral == 0 && localForward >= -10 && localForward <= 34
                && (y == top || y == top - 1)) {
            return localForward % 5 == 0
                    ? Blocks.IRON_BLOCK.defaultBlockState()
                    : Blocks.CONCRETE.pick(DyeColor.ORANGE).defaultBlockState();
        }
        if (localLateral == 0 && (localForward == 22 || localForward == 33)
                && y >= top - 10 && y < top - 1) {
            return Blocks.IRON_CHAIN.defaultBlockState();
        }
        if (localLateral == 0 && localForward == 33 && y == top - 11) {
            return Blocks.IRON_BLOCK.defaultBlockState();
        }
        return null;
    }

    private static boolean isPortshipEdge(int forward, int lateral) {
        if (!portshipContains(forward, lateral)) return false;
        return !portshipContains(forward + 1, lateral)
                || !portshipContains(forward - 1, lateral)
                || !portshipContains(forward, lateral + 1)
                || !portshipContains(forward, lateral - 1);
    }

    private static BlockState containerColor(long hash) {
        DyeColor color = CONTAINER_COLORS[
                Math.floorMod((int) (hash ^ (hash >>> 32)), CONTAINER_COLORS.length)];
        return Blocks.CONCRETE.pick(color).defaultBlockState();
    }

    private static int signedRange(long value, int radius) {
        return Math.floorMod((int) (value ^ (value >>> 32)), radius * 2 + 1) - radius;
    }

    private static double unit(long value) {
        return (value >>> 11) * 0x1.0p-53;
    }
}
